name: Deploy Frontend to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Angular dependencies
      run: npm install
      # working-directory: ./browser

    - name: Build Angular application
      run: npx ng build --configuration=production
      # working-directory: ./browser

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Deploy Angular Frontend to Firebase Hosting
      run: firebase deploy --only hosting --token "${{ secrets.FIREBASE_TOKEN }}" --project task-app-293dd
      # working-directory: ./browser
